import { useState } from 'react';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import Error from 'next/error';

import {
  Htag,
  Button,
  Paragrath,
  Tag,
  Rating,
  Input,
  Textarea
} from '@/components';
import { withLayout } from '@/layout/Layout';
import { MenuItem } from '@/interfaces/menu.interface';
import { API } from '@/helpers/api';

function Home({ menu }: HomeProps) {
  const [rating, setRating] = useState<number>(4);

  return <Error statusCode={404} />;

  return (
    <>
      <Head>
        <title>OWL top</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link key={1} rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Htag tag="h3">aaa</Htag>
        <Button appearance="primary">click me</Button>
        <Button appearance="ghost" arrow="right">
          click me
        </Button>
        <Paragrath size="l">sss</Paragrath>
        <Paragrath size="m">sss</Paragrath>
        <Paragrath size="s">sss</Paragrath>
        <Tag size="s" color="red">
          teg
        </Tag>
        <Tag size="m" color="green" href="mail.ru">
          teg
        </Tag>
        <Tag size="s" color="primary">
          teg
        </Tag>
        <Tag size="s" color="ghost">
          teg
        </Tag>
        <Tag size="s" color="grey">
          teg
        </Tag>
        <Rating rating={rating} isEditable setRating={setRating} />
        <Input placeholder="test" />
        <Textarea placeholder="test"></Textarea>
      </main>
    </>
  );
}

export default withLayout(Home);

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const firstCategory = 0;
  const { data: menu } = await axios.post<MenuItem[]>(API.topPage.find, {
    firstCategory
  });
  return {
    props: {
      menu,
      firstCategory
    }
  };
};

interface HomeProps extends Record<string, unknown> {
  menu: MenuItem[];
  firstCategory: number;
}
