name: LINT

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 18.14.0

      - name: npm install
        run: npm install

      - name: Stylelint check
        run: npm run stylelint

      - name: Typescript check
        run: npm run lint